# __INTRODUCTION__ 
###### _Today's Class was By From Haribabu Sir_:
We go through ML in three approaches mathematics, programming, and intuition.

Artificial Intelligence: We, humans are trying to impart knowledge or intelligence to the machines to make changes in the day to day world. Mimicking human intelligence in humans.

Evolutionary organisms, Machine learning. Humans basically learn from experiences but machines follow the instruction given by us. This is Traditional Programming. But we now want humans to learn from experience too. More metaphorically learn from data. Which is Training the machine for machine learning.

In ML terminalogy equations which are found are called to be model. Hyperplanes are imaginary multidimensional planes which are built by computers. Predicting a definite value is known as Regression in ML  and Predicting the category of class or range is known as classification.


In ML we already have the 'Ground Truth' Or Target (y , Label). 2 categories- binary classification else Multi class classification. Why do we need DL when ML is already there?

## __Neural Networks:__
###### _A Game Changer Perceptron, Forward Propagation_

When we combine number of Gates we get transistors. Neural Network is highly inspired by the Biological Neuron. Transformers are based on encoder decoder architectures. Feed forward Networks are also essential. 

In [17]:
def func(x):
    return 2*x+1
print(func(int(input())))

5


Let's implement the same with an array.

_A 2 dimensional array multiplied by a scalar quantity and then added by one._

In [14]:
import numpy as np
import random
a=np.random.randint(1,3,(3,3))
def func1(a):
    print(a)
    return 2*a+1
print(func1(a))

[[1 1 1]
 [1 2 2]
 [2 1 2]]
[[3 3 3]
 [3 5 5]
 [5 3 5]]


_Now moving forward towards matrix multiplication..._

In [27]:
c=np.random.randint(1,3,(3,3))
d=np.random.randint(1,4,(3,3))
def multiplicationofmatrices(x,y):
    y=x*y
    return y
print(multiplicationofmatrices(c,d))

[[2 3 2]
 [1 1 2]
 [1 2 2]]


__Now Implementing the above using TENSORS__

In [29]:
import torch
e=torch.randint(1,3,(3,3))
f=torch.randint(1,3,(3,3))
def multiplicationoftensor(x,y):
    y=x*y
    return y
print(multiplicationofmatrices(e,f))

tensor([[4, 2, 1],
        [4, 4, 1],
        [4, 1, 4]])


Remember, `tensor.random` has no attribute such as `randint`

## __Steps in Deep Learning:__ (_Starting with Simple Perceptron_):
__Step 1: Data Preparation__: _Processing the Data, Preprocessing, Visualizing the Data, Having the Truth Value._

__Step 2: Model Design__: _Neural Network Architecture, Actualize Parameters._

__Step 3: Forward Propagation__: _Feeding the input to the model. We get the predicted value here._

__Step 4: Loss Calculation__: _Difference between Predicted Value and Truth Value. (ex. Mean Square Error, Binary Cross Entropy)_

__Step 5: Optimazation__: _We try to reduce the loss _

# __FEW POINTS__:
###### _That I thought are important and Intresting_
MAE,MSE Loss Calculation functions are most suitable for Regression. 
__MAE vs MSE in terms of Outliers__:

__MAE (Mean Absolute Error)__: Less sensitive to outliers because it calculates the absolute difference, avoiding squared amplification.

__MSE (Mean Squared Error)__: Highly sensitive to outliers since squaring large errors makes them dominate the loss.

We need to get or choose the best values of w and b so that they could be precise to the Truth Values. We should be able to or atleast try to increase 'w' and decrease 'b' for better pattern learning and reduced dependency on constant shifts in our Neural Network.

We use different gradients in this case for the redution of Loss. Which is really very similar to the Derivative Formula.
So we have to move near to the Optima in both the cases such as Positive Slope and Negative Slope. This is known as convergence. 

We have to be far from the saddle points in this case since gradients in saddle points is zero which means zero progress in finding the loss. The learning rate ($\alpha$) controls the step size of updates in gradient descent. Which if is bigger than shall oscillate more and if is smaller then shall be time taking so it must be balanced. 
Use MAE for robust models and MSE when penalizing large errors heavily is desired.

__Note__: An __Outlier__ is a data point that significantly deviates from the rest of the dataset. It may indicate variability, errors, or anomalies.
_Example_: A house priced at $10M in a dataset where most houses cost $100K–$500K.

##### __Simple Gradient Descent Algorithm:__

```python
t=0
epochs=3
while(t<=epochs):
    w=w-learningRate*dw
    b=b-learningRate*db
    t+=1
``` 

This is a **gradient descent algorithm** for updating weights ($w$) and bias ($b$) over a specified number of iterations (epochs).

### Explanation:
1. **Initialization**:  
   Start with $t = 0$ (iteration counter) and a defined number of epochs.

2. **Update Rules**:  
   At each iteration, the weights and bias are updated using:  
   $$ w = w - \alpha \cdot \frac{\partial J}{\partial w} $$  
   $$ b = b - \alpha \cdot \frac{\partial J}{\partial b} $$  
   where:
   - $\alpha$ is the learning rate.
   - $\frac{\partial J}{\partial w}$ and $\frac{\partial J}{\partial b}$ are gradients of the cost function $J$ w.r.t. $w$ and $b$.

3. **Iteration**:  
   The updates are repeated for `epochs` times, incrementing $t$ after each update.

### Purpose:  
The algorithm minimizes the cost function $J(w, b)$ by iteratively adjusting $w$ and $b$ to reduce the error between predictions and actual values.